### PR TITLE
Removed the AFH home page as a download link

### PR DESCRIPTION
**Pull request by vbajs**
And also added something to tell that you must replace the [URL= with the download link

### CODE REVIEW

**Comment by r-matlock** [comment]
Thanks for the suggestion, but this is intentional. This link points to the AFH of @MZO9400 who is currently hosting our builds on his AFH account.

**Comment by vbajs** [comment]
OK, but when I am opening a thread, can I replace this link with my link?

**Comment by MZO9400** [comment]
If you're gonna go official then no, I'll provide with ftp and afh login details, you'll have to upload builds there. If you're going unofficial then sure you can.

**Comment by vbajs** [comment]
Actually, I am thinking of making my builds official for jfltexx but my frist build for this is basicly gonna be an unofficial and test build,
If everything went well, then upcoming build will be official otherwise upcoming build will be unofficial and test build that's not available for anyone ._.

**Comment by MZO9400** [comment]
Sure then you can make your unofficial build, test it and then once you're ready to go official, send one of us a Hangout and we'll help you there. But for officials you're gonna need to follow the template and use the given download link.

**Comment by MZO9400** [comment]
We've made a conversation at Hangouts @vbajs. I hope we can get it all sorted there :)

**Pull request closed without merging**
